### PR TITLE
Added support for unicode email addresses

### LINKED ISSUE #100: Unicode email address
Hi,

I'm trying to send some emails to addresses containing unicode characters. Example:
`KYÖSTI@example.org`. However, when I'm trying to send the email I'm getting:

> SendGridClientError: (400, '{"message": "error", "errors": ["Invalid email address KY\\u00d6STI@example.org"]}')

As you can see, for some reason it's double encoding the email address somewhere so `\u00d6` becomes `\\u00d6`

Any suggestions? 

I've tried making it work in a very large number of ways (various encodings, using `parse_and_add()` directly etc.), but to no success so far.

### PR DESCRIPTION
**Pull request by tushdante**
- This isin't working just yet, still getting an issue with sendgrid not recognizing any characters after the encoded one
- Closes #100

### CODE REVIEW

**Comment by elbuo8** [comment]
@thinkingserious was this resolved somewhere else?

**Comment by thinkingserious** [comment]
This is not a library issue, it's a feature that SendGrid does not support.

**Comment by elbuo8** [comment]
SG doesn't support Unicode? That is really odd.

**Comment by elbuo8** [comment]
Oh, in an email address.

**Pull request closed without merging**
