### PR TITLE
Add use case for generation of Plain Text Content from HTML

### LINKED ISSUE #354: Auto Generate Plain Text Content from HTML
We require both HTML and Plain Text content for improved deliverability. In some cases, only HTML may be available. We need a function that automatically converts a given HTML string to the Plain Text equivalent.

### PR DESCRIPTION
**Pull request by cmccandless**
# Fixes #354

### Checklist
- [x] I have made a material change to the repo (functionality, testing, spelling, grammar)
- [x] I have read the [Contribution Guide] and my PR follows them.
- [x] I updated my branch with the ~master~ v4 branch.
- [x] I have added necessary documentation about the functionality in the appropriate .md file
- [x] I have added in line documentation to the code I modified

### Short description of what this PR does:
- Resolves #354 by adding a use case for generating plain text when only HTML content is available.

### CODE REVIEW

**Comment by thinkingserious** [comment]
Hello @cmccandless,<br /><br/>Thanks again for the PR!<br />                                              <br />It's <a href="https://sendgrid.com/blog/hacktoberfest-2018-has-arrived/">HACKTOBERFEST</a>! We want to show our appreciation by sending                                              you some special Hacktoberfest swag. If you have not already, could you please fill out                                              <a href="https://dx.sendgrid.com/hacktoberfest/join">this form</a> so we can send it to you? Thanks!                                             <br /><br />Team SendGrid DX

**Comment by thinkingserious** [comment]
Hello @cmccandless,

Could you please merge this against our [v4 branch](https://github.com/sendgrid/sendgrid-python/tree/v4)? Thank you!

With Best Regards,

Elmer

**Comment by cmccandless** [comment]
> Could you please merge this against our v4 branch? Thank you!

Done. This PR was already merging against that branch, but I did rebase against the latest commits in v4.

**Comment by thinkingserious** [comment]
Hello @cmccandless,<br /><br/>Thanks again for the PR!<br /><br />                                         You have earned 10 out of the 5 points needed to receive glorious SendGrid Hacktoberfest swag.<br /><br />                                         Please take a moment to checkout <a href="https://dx.sendgrid.com/hacktoberfest/issues">this link</a> to find more issues to get you past the required threshold or to simply continue the celebration.<br /><br />                                         Also, <strong>please be sure you have officially registered with us <a href="https://dx.sendgrid.com/hacktoberfest/join">here</a> by November 1, 2018</strong> to qualify.<br /><br />                                         If you have any questions you can email us at <a href="mailto:dx+hacktoberfest2018@sendgrid.com">dx+hacktoberfest2018@sendgrid.com</a>.<br /><br />                                         Thank you and Happy Hacktobering!<br /><br />                                         Team SendGrid

**Comment by cmccandless** [comment]
Labels indicate that something further is expected of me, but I have already rebased against v4, and there are no requested changes. Is there anything else needed from me?

**Comment by thinkingserious** [comment]
Thanks for the heads up @cmccandless, this PR has been updated accordingly.

**Comment by thinkingserious** [comment]
Hello @cmccandless,<br /><br/>Thanks again for the PR!<br />                                              <br />We appreciate your contribution and look forward to                                              continued collaboration. Thanks!                                             <br /><br />Team SendGrid DX

**Pull request merged**
