### PR TITLE
(WIP) Fix failing TravisCI builds

### LINKED ISSUE #368: TravisCI is failing on a dependency
#### Issue Summary

It looks like there may be a dependency issue that needs to be resolved. In the logs, there is a deprecation warning. 

#### Steps to Reproduce

1. Make a PR
2. Wait
3. Travis fails, click Details
4. Click the red box and get the error `python setup.py install failed and exited with 1` 

> Installed /tmp/easy_install-xVxFSM/unittest2-1.1.0/.eggs/traceback2-1.4.0-py2.6.egg
> Searching for linecache2
> Reading https://pypi.python.org/simple/linecache2/
> Downloading https://pypi.python.org/packages/44/b0/963c352372c242f9e40db02bbc6a39ae51bde15dddee8523fe4aca94a97e/linecache2-1.0.0.tar.gz#md5=7b25d0289ec36bff1f9e63c4329ce65c
> Best match: linecache2 1.0.0
> Processing linecache2-1.0.0.tar.gz
> Writing /tmp/easy_install-xVxFSM/unittest2-1.1.0/temp/easy_install-X88hlg/linecache2-1.0.0/setup.cfg
> Running linecache2-1.0.0/setup.py -q bdist_egg --dist-dir /tmp/easy_install-xVxFSM/unittest2-1.1.0/temp/easy_install-X88hlg/linecache2-1.0.0/egg-dist-tmp-Y4r0ft
> /home/travis/virtualenv/python2.6.9/lib/python2.6/site-packages/setuptools/dist.py:26: DeprecationWarning: Do not call this function
>   warnings.warn("Do not call this function", DeprecationWarning)
> ERROR:root:Error parsing

### PR DESCRIPTION
**Pull request by cmccandless**
Resolves #368

### CODE REVIEW

**Comment by SendGridDX** [comment]
[CLA assistant check](https://cla.sendgrid.com/sendgrid/sendgrid-python?pullRequest=369) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.sendgrid.com/sendgrid/sendgrid-python?pullRequest=369) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.sendgrid.com/check/sendgrid/sendgrid-python?pullRequest=369) it.</sub>

**Comment by mbernier** [comment]
@cmccandless Why did you close this PR?

**Comment by cmccandless** [comment]
@mbernier See last comment on #368. @thinkingserious had a better solution.

**Comment by thinkingserious** [comment]
@cmccandless

We have not been able to merge your Pull Request, but because you are awesome - we wanted to make sure you could still get a SendGrid Hacktoberfest shirt.  

Please go **fill [out our swag form](https://dx.sendgrid.com/swag) before Nov 5th** and we will send the shirt! (We know that you might have tried this before and it didn’t work, sorry about that!)

### **You have till Nov 5th to fill out this form** in order to get the Hacktoberfest shirt!

Thank you for contributing during Hacktoberfest! We hope to see you in the repos soon! Just so you know, we always give away a SendGrid shirt for your first ever non-Hacktoberfest PR that gets merged.

**Pull request closed without merging**
