### PR TITLE
Provide utf-8 as encoding explicitly when opening text files

### PR DESCRIPTION
**Pull request by rshest**
When opening text files in few places, the code relies on system default encoding being set to UTF-8.

This is safe enough in general, but there are certain corner cases like #379, where default one is e.g. ASCII (for whatever reason).

The pull request changes code to use UTF-8 encoding explicitly, without relying on the system defaults.

EDIT: There is another commit fixing a unit test (`test_asm_display_group_limit`), since that was failing the build, coming from master rebase. 

EDIT2: The "reduced" code coverage is because of added import statements - so this is a false positive in fact.

### CODE REVIEW

**Comment by SendGridDX** [comment]
[CLA assistant check](https://cla.sendgrid.com/sendgrid/sendgrid-python?pullRequest=414) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.sendgrid.com/sendgrid/sendgrid-python?pullRequest=414) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.sendgrid.com/check/sendgrid/sendgrid-python?pullRequest=414) it.</sub>

**Comment by gabrielkrell** [comment]
Looks good.  You can also do `from io import open` to ease the eventual move to Python 3 (where regular `open` has an `encoding` parameter) ([source](https://stackoverflow.com/a/10971047/)).

**Comment by rshest** [comment]
Good point, thanks. Done :)

**Comment by mbernier** [comment]
@rshest

We have not been able to merge your Pull Request, but because you are awesome - we wanted to make sure you could still get a SendGrid Hacktoberfest shirt.  

Please go **fill [out our swag form](https://dx.sendgrid.com/swag) before Nov 5th** and we will send the shirt! (We know that you might have tried this before and it didn’t work, sorry about that!)

### **You have till Nov 5th to fill out this form** in order to get the Hacktoberfest shirt!

Thank you for contributing during Hacktoberfest! We hope to see you in the repos soon! Just so you know, we always give away a SendGrid shirt for your first ever non-Hacktoberfest PR that gets merged.

**Comment by thinkingserious** [comment]
Hello @rshest,<br /><br/>Thanks again for the PR!<br />                                              <br />We appreciate your contribution and look forward to                                              continued collaboration. Thanks!                                             <br /><br />Team SendGrid DX

**Pull request merged**
