### PR TITLE
Create a Use Case directory

### LINKED ISSUE #528: Create a Use Cases Directory
Due to the success we have seen from hacktoberfest, we are seeing more people create use cases. This is amazing! 
We want to make sure that everyone can find them. Please help us to break up this file and make it easier to read and manage:
- Create a Use Cases Directory
- Put a README.md in this directory
- Make a file in the new directory for each individual Use Case from USE_CASES.md, copy the content to this file
- For each file you've created, link to it from the README you created
- Organize the links in the README by type
- Make sure the names of the files you created are related to the Use Case
Thank you!

### PR DESCRIPTION
**Pull request by AnnaDodson**
# Resolves #528 

### Checklist
- [x] I have made a material change to the repo (functionality, testing, spelling, grammar)
- [x] I have read the [Contribution Guide] and my PR follows them.
- [x] I updated my branch with the master branch.
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation about the functionality in the appropriate .md file
- [ ] I have added in line documentation to the code I modified

### Short description of what this PR does:
- Move use cases from `USE_CASES.md` into `use-cases` directory
- Split use cases into separate files for better readability

If you have questions, please send an email to [Sendgrid](mailto:dx@sendgrid.com), or file a Github Issue in this repository.

### CODE REVIEW

**Comment by SendGridDX** [comment]
[CLA assistant check](https://cla.sendgrid.com/sendgrid/sendgrid-python?pullRequest=530) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.sendgrid.com/sendgrid/sendgrid-python?pullRequest=530) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.sendgrid.com/check/sendgrid/sendgrid-python?pullRequest=530) it.</sub>

**Comment by gabrielkrell** [comment]
Uh oh, looks like this overlaps with #529.

**Comment by AnnaDodson** [comment]
Yes it looks ,like #529 didn't realise I was working on it. They both look similar apart from categorization of use cases in the readme so I think either can merge in.

**Comment by thinkingserious** [comment]
@AnnaDodson

We have not been able to merge your Pull Request, but because you are awesome - we wanted to make sure you could still get a SendGrid Hacktoberfest shirt.  

Please go **fill [out our swag form](https://dx.sendgrid.com/swag) before Nov 5th** and we will send the shirt! (We know that you might have tried this before and it didn’t work, sorry about that!)

### **You have till Nov 5th to fill out this form** in order to get the Hacktoberfest shirt!

Thank you for contributing during Hacktoberfest! We hope to see you in the repos soon! Just so you know, we always give away a SendGrid shirt for your first ever non-Hacktoberfest PR that gets merged.

**Pull request closed without merging**
