### PR TITLE
Updated link to direct to #L9

### PR DESCRIPTION
**Pull request by vinayak42**
@misterdorm The link to /mail/send Helper looked fine. Please provide details as to where it should direct to.

# Fixes #633 

### Checklist
- [x] I have made a material change to the repo (functionality, testing, spelling, grammar)
- [x] I have read the [Contribution Guide] and my PR follows them.
- [x] I updated my branch with the master branch.
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation about the functionality in the appropriate .md file
- [ ] I have added in line documentation to the code I modified

### Short description of what this PR does:
- Made changes to #633 

If you have questions, please send an email to [SendGrid](mailto:dx@sendgrid.com), or file a GitHub Issue in this repository.

### CODE REVIEW

**Comment by thinkingserious** [comment]
Hello @vinayak42,<br /><br/>Thanks again for the PR!<br />                                              <br />It's <a href="https://sendgrid.com/blog/hacktoberfest-2018-has-arrived/">HACKTOBERFEST</a>! We want to show our appreciation by sending                                              you some special Hacktoberfest swag. If you have not already, could you please fill out                                              <a href="https://dx.sendgrid.com/hacktoberfest/join">this form</a> so we can send it to you? Thanks!                                             <br /><br />Team SendGrid DX

**Comment by thinkingserious** [comment]
Hello @vinayak42,

Could you please merge this against our [v4 branch](https://github.com/sendgrid/sendgrid-python/tree/v4)? Thank you!

With Best Regards,

Elmer

**Comment by vinayak42** [comment]
@thinkingserious Changed the branch  to sendgrid:v4, anything else to be done?

**Comment by misterdorm** [comment]
@vinayak42  Looks like you may have merged the v4 branch in, which included everything from master, vs. rebasing your branch against v4.  Could you please rebase instead of merging them together?   Thanks.

**Comment by thinkingserious** [comment]
Hello @vinayak42,<br /><br/>Thanks again for the PR!<br /><br />                                         You have earned 5 out of the 5 points needed to receive glorious SendGrid Hacktoberfest swag.<br /><br />                                         Please take a moment to checkout <a href="https://dx.sendgrid.com/hacktoberfest/issues">this link</a> to find more issues to get you past the required threshold or to simply continue the celebration.<br /><br />                                         Also, <strong>please be sure you have officially registered with us <a href="https://dx.sendgrid.com/hacktoberfest/join">here</a> by November 1, 2018</strong> to qualify.<br /><br />                                         If you have any questions you can email us at <a href="mailto:dx+hacktoberfest2018@sendgrid.com">dx+hacktoberfest2018@sendgrid.com</a>.<br /><br />                                         Thank you and Happy Hacktobering!<br /><br />                                         Team SendGrid

**Comment by vinayak42** [comment]
@thinkingserious @misterdorm Apologies for the inconvenience. I am having some issues about rebasing this to v4. Could you trace the exact steps/commands to do the same in GitHub?

**Comment by misterdorm** [comment]
@vinayak42  It's probably easiest to start with a new branch, branched from `v4`, and then merge/apply your commits onto that branch.  And then force push to this PR.

**Comment by thinkingserious** [comment]
Hello @vinayak42,

Do you mind resubmitting this PR, but against the v4 branch?

Thanks!

With Best Regards,

Elmer

**Pull request merged**
