### PR TITLE
All prints implemented with Python3 style

### PR DESCRIPTION
**Pull request by martinvol**

### CODE REVIEW

**Comment by thinkingserious** [comment]
Hello @martinvol,<br /><br/>Thank you for the PR!<br />                                              <br />We will be reviewing this PR soon, in the mean                                              time, if you have not, please be sure to                                              <a href="https://github.com/sendgrid/sendgrid-python/blob/master/CONTRIBUTING.md#cla">                                             sign our CLA</a> so that we can merge your changes. Thanks again!                                             <br /><br />Team DX

**Comment by thinkingserious** [comment]
Hello @martinvol,

As of today, we have not received your [signed CLA](https://github.com/sendgrid/sendgrid-python/blob/master/CONTRIBUTING.md#cla). Are you still interested in merging your PR?

Thanks!

With Best Regards,

Elmer

**Comment by martinvol** [comment]
Hi @thinkingserious, I don't have a printer and I kinda have to get out of my way to get one (I'm remote). Do you have a digital document I could sign?

**Comment by thinkingserious** [comment]
Hi @martinvol,

Yes, according to the CLA, you may:

"You may also provide the information requested below along with the statement “I accept these terms” in the body of an email, attach the copy of these terms you received from us to that email, and send the email to us at [email address]."

Thanks!

**Comment by martinvol** [comment]
I just send it!

**Comment by thinkingserious** [comment]
Hello @martinvol,

I have not yet received it. Was it sent to dx@sendgrid.com?

Thanks!

**Comment by martinvol** [comment]
Yes, with subject "SendGrid Contributor Agreement"

**Comment by thinkingserious** [comment]
Ah, just found it. It was in SPAM :(

Thanks!

**Comment by martinvol** [comment]
is this going to get merged?

**Comment by thinkingserious** [comment]
Hello @martinvol,

This PR is still climbing up our backlog. There are still quite a few ahead. 

The PR can gain priority if other +1 or comment on this PR.

Thanks!

Elmer

**Comment by iandouglas** [comment]
+1 :)

**Comment by kevin-brown** [comment]
> The PR can gain priority if other +1 or comment on this PR.

Does this include the "reactions" that can be added to the OP, or only actual comments? (asking for the future)

**Comment by thinkingserious** [comment]
@kevin-brown,

Yes, reactions count too.

Generally, any unique activity on this thread will contribute to it's prioritization.

**Comment by thinkingserious** [comment]
Thanks again @martinvol,

Please take a moment to fill out [this form]( https://docs.google.com/forms/d/e/1FAIpQLSelP4uF-wGJebxVYq1DYw5WzHomEUauab3YiqrshyCkRs0fqw/viewform#start=invite) so that we can send you some swag :)

**Pull request merged**
