### PR TITLE
Add slack event integration

### LINKED ISSUE #362: Create a tutorial to create a Slack event integration with Python using this SDK
Create a tutorial that explains how to create a simple [integration with Slack](https://api.slack.com/events-api) that allows an email to be triggered based on some [defined event](https://api.slack.com/events).

The example should utilize best practices for storing credentials.

Please add the tutorial to USE_CASES.md.

### PR DESCRIPTION
**Pull request by navinpai**
# Fixes # 
Fixes #362

### Checklist
- [x] I have made a material change to the repo (functionality, testing, spelling, grammar)
- [x] I have read the [Contribution Guide] and my PR follows them.
- [x] I updated my branch with the master branch.
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation about the functionality in the appropriate .md file
- [x] I have added in line documentation to the code I modified

### Short description of what this PR does:
- Updated USE_CASES.md to include example on how to integrate sendgrid python API with slack events API to trigger emails from slack events
- Fixes #362

If you have questions, please send an email to [Sendgrid](mailto:dx@sendgrid.com), or file a Github Issue in this repository.

### CODE REVIEW

**Comment by SendGridDX** [comment]
[CLA assistant check](https://cla.sendgrid.com/sendgrid/sendgrid-python?pullRequest=478) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.sendgrid.com/sendgrid/sendgrid-python?pullRequest=478) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.sendgrid.com/check/sendgrid/sendgrid-python?pullRequest=478) it.</sub>

**Comment by af4ro** [comment]
Hey @navinpai,
Could you please resolve the merge conflicts so that we could merge this into our latest update!

We appreciate your time and contribution!

**Comment by af4ro** [comment]
Thank you so much for the prompt response @navinpai!

**Comment by thinkingserious** [comment]
Hello @navinpai,<br /><br/>Thanks again for the PR!<br />                                              <br />We appreciate your contribution and look forward to                                              continued collaboration. Thanks!                                             <br /><br />Team SendGrid DX

**Pull request merged**
