### PR TITLE
TypeError: get expected at least 1 arguments, got 0

### PR DESCRIPTION
**Pull request by yamamanx**
key.get() 
TypeError: get expected at least 1 arguments, got 0

### CODE REVIEW

**Comment by SendGridDX** [comment]
[CLA assistant check](https://cla.sendgrid.com/sendgrid/sendgrid-python?pullRequest=305) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.sendgrid.com/sendgrid/sendgrid-python?pullRequest=305) before we can accept your contribution.<br/><hr/>**山下光洋** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.sendgrid.com/check/sendgrid/sendgrid-python?pullRequest=305) it.</sub>

**Comment by yamamanx** [comment]
Thanks @thinkingserious,

code example is below.

Best Regards.

```
import sendgrid
from sendgrid.helpers.mail import *

sg = sendgrid.SendGridAPIClient(apikey=SG_API_KEY)
from_email = Email('exampla@mydomain.com')
to_email = Email('exampla@mydomain.com')
body = 'Hello'
content = Content('text/plain', body)
    
mail = Mail(from_email, subject, to_email, content)

custom_arg = {'body' : body}
mail.add_custom_arg(custom_arg)

response = sg.client.mail.send.post(request_body=mail.get())
```

**Comment by SendGridDX** [comment]
Thanks @yamamanx,

It looks like we still need your [signed CLA](https://cla.sendgrid.com/sendgrid/sendgrid-python?pullRequest=305). Do you have any issues with signing it?

Thanks!

Elmer

**Comment by thinkingserious** [comment]
Hi @yamamanx,

If you prefer not to sign the CLA, we can make the fixes on our end. Is that OK?

Thanks!

**Comment by yamamanx** [comment]
Thanks @thinkingserious,

It's okay.
I signed CLA.

Best Regards.

**Comment by thinkingserious** [comment]
Thanks @yamamanx!

**Comment by thinkingserious** [comment]
Hi @yamamanx,

It looks like there was an issue with the CLA. Could you please check the error above? https://github.com/sendgrid/sendgrid-python/pull/305#issuecomment-290306493

It looks like your email address needs to be updated.

Thanks!

**Comment by thinkingserious** [comment]
Thanks for updating the CLA! Looks like the first commit was made by [another account](https://github.com/sendgrid/sendgrid-python/pull/305/commits). (maybe it was deleted?)

Now, it looks like we need the tests to be updated to reflect your changes. Could you please [take a look](https://travis-ci.org/sendgrid/sendgrid-python/builds/223020795)? Thanks!

**Comment by yamamanx** [comment]
Hi @thinkingserious,

Sorry....

I mistook using "add_custom_arg"

**Pull request closed without merging**
