### PR TITLE
Addition of template use code snippet

### PR DESCRIPTION
**Pull request by datamafia**
Did not see a clear example in docs or associated SG work. Save a dev like me a few minutes of google time by adding this prototype to example.

### CODE REVIEW

**Comment by elbuo8** [comment]
Thanks for contributing to SendGrid Open Source! We think it's awesome when community members contribute to our projects and want to celebrate that.

The following link will ask you to authenticate with Github (so we can verify your identity), it will then ask for a little bit more information and we'll then send you a thanks for contributing.

**[Click Here to Continue »](http://contribot.com/auth)**

Once again, thank you!

**Comment by heitortsergent** [comment]
Thanks @datamafia!

I'll be updating the README soon, here's our docs reference to it:

https://sendgrid.com/docs/API_Reference/Web_API_v3/Template_Engine/smtpapi.html

**Comment by datamafia** [comment]
Glad I could help, albeit in such a minor way. I would like to point out that this is not a bug or functionality concern, luckily. 

Regardless, the time to review, respond, and merge does concern me with respect to SG team's agility and awareness. Over 2 months is rather long and I must admit that I am on a personal crusade against companies posting "open source" when actually they are abandoning code on GitHub. 

Your thoughts are very welcome. The aforementioned crusade is best categorized as stewardship in programming. Code abandonment is a legitimate issue.

I am a fan of your product, nothing diminished.

As for contribot, no thanks.

**Comment by brandonmwest** [comment]
Hi Marc, hope you're doing well. Thanks a lot for your contribution and sorry for the delay. These libraries are definitely not abandoned -- we pushed a new package to PyPI on 12/31. That said, we do have some new APIs and libraries coming soon that have been taking more of our attention recently, so we've been prioritizing minor changes a bit lower. Appreciate your feedback and thanks for using SendGrid.

**Comment by datamafia** [comment]
Thanks, I do understand. A final footnote:

As a developer, I am constantly making decisions on services, libs, etc for those who pay for my services. A large contributing factor to final decision making for service selection is based on perceived responsiveness in GitHub and other media. Apologies for any unnecessary crusading, but SG has a "soft spot" in my heart. Integration of a service is a serious investment, please consider what tools and breadcrumbs are left in the public domain, including, but not limited to inaction. Ergo GH and other similar services '_advertise_' directly to the people with influence on product adoption in the enterprise marketplace.

PS - __shout out__ to @brandonmwest -- not talked since the days when you were #1 for WM (120th ave)  - hope all is well.

**Comment by elbuo8** [comment]
@datamafia I want to personally apologize for this taking so long. I manage all my github issues over email and I completely missed the original one until this conversation got going. Thank you for being a contributor and an excellent member of the community.

**Pull request merged**
