### PR TITLE
making code pep8 compllient

### LINKED ISSUE #464: Pep8 Compliance
#### Issue Summary
According to this report, there are a lot of Pep8 issues. Can you fix them? 

https://codeclimate.com/github/sendgrid/sendgrid-python/pull/463

#### Acceptance criteria: 
Code climate should pass when you make your PR.

### PR DESCRIPTION
**Pull request by gardlt**
# Fixes #464

### Checklist
- [x] I have made a material change to the repo (functionality, testing, spelling, grammar)
- [x] I have read the [Contribution Guide] and my PR follows them.
- [x] I updated my branch with the master branch.
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation about the functionality in the appropriate .md file
- [ ] I have added inline documentation to the code I modified

### Short description of what this PR does:
- made code pep8 compliant
- 

If you have questions, please send an email to [Sendgrid](mailto:dx@sendgrid.com), or file a Github Issue in this repository.

### CODE REVIEW

**Comment by SendGridDX** [comment]
[CLA assistant check](https://cla.sendgrid.com/sendgrid/sendgrid-python?pullRequest=495) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.sendgrid.com/sendgrid/sendgrid-python?pullRequest=495) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.sendgrid.com/check/sendgrid/sendgrid-python?pullRequest=495) it.</sub>

**Comment by mbernier** [comment]
If you are interested, we would love the opportunity to talk to you about Hacktoberfest and our API libraries.

Our agenda would be: Explore what you liked and is there anything we can do to improve? 

You can grab a time [on my calendar](https://calendly.com/matt-bernier/30min) that works for you and we can have a chat on Google Hangout or Skype. If you prefer, you can email me using my GitHub username at my company’s domain.

Thank you so much,

Matt Bernier - @mbernier - SendGrid Developer Experience Product Manager
Elmer Thomas - @thinkingserious - SendGrid Developer Experience Engineer
@SendGrid

**Comment by thinkingserious** [comment]
Hi @gardlt,

Just checking in on why you closed this issue. Thanks!

**Comment by gardlt** [comment]
I am not able to continue working on the issue, changes are still here, but making use I don't hog it.

**Comment by thinkingserious** [comment]
Thanks for the update @gardlt,

If you get more time to work on it, please feel free to reopen.

With Best Regards,

Elmer

**Pull request closed without merging**
