### PR TITLE
# Fixes #500

### LINKED ISSUE #500: Fix "similar-code" issue in sendgrid/helpers/mail/mail.py
Similar blocks of code found in 3 locations. Consider refactoring.

https://codeclimate.com/github/sendgrid/sendgrid-python/sendgrid/helpers/mail/mail.py#issue_59f639d0343eae000100009e

### PR DESCRIPTION
**Pull request by extemporalgenome**
### Checklist
- [x] I have made a material change to the repo (functionality, testing, spelling, grammar)
- [x] I have read the [Contribution Guide] and my PR follows them.
- [x] I updated my branch with the master branch.
- [x] (transparent change): I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation about the functionality in the appropriate .md file
- [x] I have added in line documentation to the code I modified

### Short description of what this PR does:
- Fixes CodeClimate style issue.

@mbernier edit:
Fixes #500

### CODE REVIEW

**Comment by SendGridDX** [comment]
[CLA assistant check](https://cla.sendgrid.com/sendgrid/sendgrid-python?pullRequest=512) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.sendgrid.com/sendgrid/sendgrid-python?pullRequest=512) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.sendgrid.com/check/sendgrid/sendgrid-python?pullRequest=512) it.</sub>

**Comment by extemporalgenome** [comment]
I see other issues in code-climate. I'll add fixes for at least most of those to this PR.

**Comment by thinkingserious** [comment]
@extemporalgenome

We have not been able to merge your Pull Request, but because you are awesome - we wanted to make sure you could still get a SendGrid Hacktoberfest shirt.  

Please go **fill [out our swag form](https://dx.sendgrid.com/swag) before Nov 5th** and we will send the shirt! (We know that you might have tried this before and it didn’t work, sorry about that!)

### **You have till Nov 5th to fill out this form** in order to get the Hacktoberfest shirt!

Thank you for contributing during Hacktoberfest! We hope to see you in the repos soon! Just so you know, we always give away a SendGrid shirt for your first ever non-Hacktoberfest PR that gets merged.

**Comment by mbernier** [comment]
@extemporalgenome we have two things that happened with this PR - can you please look into these and fix them?

## First - one of the tests stopped passing:
```
======================================================================

FAIL: test_asm_display_group_limit (test.test_mail.UnitTests)

----------------------------------------------------------------------

Traceback (most recent call last):

  File "/home/travis/build/sendgrid/sendgrid-python/test/test_mail.py", line 472, in test_asm_display_group_limit

    self.assertRaises(ValueError, ASM, 1, list(range(26)))

AssertionError: ValueError not raised by ASM
----------------------------------------------------------------------
```
## Second - There is a merge conflict on the mail.py file:
```
    def get(self):
        """Get a response body for this Mail.

        :rtype: dict
        """
<<<<<<< issue-500
        mail = {
            'from': _get(self.from_email),
            'subject': self.subject,
            'personalizations': _get_list(self.personalizations),
            'content': _get_list(self.contents),
            'attachments': _get_list(self.attachments),
            'template_id': self.template_id,
            'sections': _merge_dicts(self.sections),
            'headers': _merge_dicts(self.headers),
            'categories': _get_list(self.categories),
            'custom_args': _merge_dicts(self.custom_args),
            'send_at': self.send_at,
            'batch_id': self.batch_id,
            'asm': _get(self.asm),
            'ip_pool_name': self.ip_pool_name,
            'mail_settings': _get(self.mail_settings),
            'tracking_settings': _get(self.tracking_settings),
            'reply_to': _get(self.reply_to),
        }

        return _trim_none(mail)
=======
        mail = {}
        if self.from_email is not None:
            mail["from"] = self.from_email.get()
        if self.subject is not None:
            mail["subject"] = self.subject

        if self.personalizations:
            mail["personalizations"] = [
                personalization.get()
                for personalization in self.personalizations
            ]

        if self.contents:
            mail["content"] = [ob.get() for ob in self.contents]

        if self.attachments:
            mail["attachments"] = [ob.get() for ob in self.attachments]

        if self.template_id is not None:
            mail["template_id"] = self.template_id

        if self.sections:
            sections = {}
            for key in self.sections:
                sections.update(key.get())
            mail["sections"] = sections

        if self.headers:
            headers = {}
            for key in self.headers:
                headers.update(key.get())
            mail["headers"] = headers

        if self.categories:
            mail["categories"] = [category.get() for category in
                                  self.categories]

        if self.custom_args:
            custom_args = {}
            for key in self.custom_args:
                custom_args.update(key.get())
            mail["custom_args"] = custom_args

        if self.send_at is not None:
            mail["send_at"] = self.send_at

        if self.batch_id is not None:
            mail["batch_id"] = self.batch_id

        if self.asm is not None:
            mail["asm"] = self.asm.get()

        if self.ip_pool_name is not None:
            mail["ip_pool_name"] = self.ip_pool_name

        if self.mail_settings is not None:
            mail["mail_settings"] = self.mail_settings.get()

        if self.tracking_settings is not None:
            mail["tracking_settings"] = self.tracking_settings.get()

        if self.reply_to is not None:
            mail["reply_to"] = self.reply_to.get()
        return mail
>>>>>>> master

    @property
    def from_email(self):
        """The email from which this Mail will be sent.

        :rtype: string
        """
        return self._from_email
```

**Comment by thinkingserious** [comment]
Thanks again for helping improve this SDK! 

We have started to execute on PR #347 (Python Mail Helper Refactor) and have integrated your work into [this branch](https://github.com/sendgrid/sendgrid-python/tree/v4). Please follow along at PR #347 to follow our progress.

With Best Regards,

Elmer

**Pull request closed without merging**
