### PR TITLE
Added PULL-REQUEST-TEMPLATE

### LINKED ISSUE #445: Create a PULL_REQUEST_TEMPLATE
#### Issue Summary

We would like to have a template for describing what has changed in the pull request being submitted.

[Github docs on this](https://help.github.com/articles/creating-a-pull-request-template-for-your-repository/) 

You can use [this file](https://github.com/sendgrid/open-source-library-data-collector/blob/master/.github/PULL_REQUEST_TEMPLATE.md) as an example

### PR DESCRIPTION
**Pull request by kira0204**
Fixes #445

### CODE REVIEW

**Comment by SendGridDX** [comment]
[CLA assistant check](https://cla.sendgrid.com/sendgrid/sendgrid-python?pullRequest=456) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.sendgrid.com/sendgrid/sendgrid-python?pullRequest=456) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.sendgrid.com/check/sendgrid/sendgrid-python?pullRequest=456) it.</sub>

**Comment by mbernier** [comment]
This rocks, thank you!!

**Comment by thinkingserious** [comment]
Hello @kira0204,<br /><br/>Thanks again for the PR!<br />                                              <br />We want to show our appreciation by sending                                              you some swag. Could you please fill out                                              <a href="https://dx.sendgrid.com/swag">this form</a> so we can send it to you? Thanks!                                             <br /><br />Team SendGrid DX

**Comment by kira0204** [comment]
Hi, sorry to bug you but I filled the form for swag once but if I click on the link again, it opens the form again. Can you please check whether my details are in the database because I didn't get any mail

**Comment by kira0204** [comment]
Hi @thinkingserious Can I know what is the status of the tshirt! I am really excited for it, thanks

**Comment by thinkingserious** [comment]
Hi @kira0204,

I will check with our swag provider and update you here. Thanks!

**Comment by thinkingserious** [comment]
Duplicate of #446

**Pull request merged**
