### PR TITLE
Add tests for Send.py

### LINKED ISSUE #417: Add tests for Send.py
#### Issue Summary

CodeCov is showing that we're missing some testing on send.py. 
[Please see their page and add some tests](https://codecov.io/gh/sendgrid/sendgrid-python/compare/db608f74fbbb4b1d4d71c644da9614de6ed900e3...86abbc199800fefe9114cab7535d28a8114cca78/src/sendgrid/helpers/inbound/send.py)

### PR DESCRIPTION
**Pull request by artiemq**
# Fixes #417 

### Checklist
- [*] I have read the [Contribution Guide] and my PR follows them.
- [*] My branch is up-to-date with the master branch.
- [*] I have added tests that prove my fix is effective or that my feature works
- [*] I have added necessary documentation (if appropriate)
- [*] All the functions created/modified in this PR contain relevant docstrings.

### Changes proposed in this pull request:
* Add test for `Send` in `send.py`
* Refactor `Send.test_payload`

### CODE REVIEW

**Comment by artiemq** [comment]
I've tried to merge master into my branch and resolve conflicts but something went wrong. 
@mbernier @thinkingserious could you review my PR?

**Comment by mbernier** [comment]
Oh wow, that is super weird. I am going to see if I can get travis to kick over a build for us. WTF Travis!?

**Comment by mbernier** [comment]
I just merged sendgrid-python master, this caused Travis to show up. 

---

If you are interested, we would love the opportunity to talk to you about Hacktoberfest and our API libraries.

Our agenda would be: Explore what you liked and is there anything we can do to improve? 

You can grab a time [on my calendar](https://calendly.com/matt-bernier/30min) that works for you and we can have a chat on Google Hangout or Skype. If you prefer, you can email me using my GitHub username at my company’s domain.

Thank you so much,

Matt Bernier - @mbernier - SendGrid Developer Experience Product Manager
Elmer Thomas - @thinkingserious - SendGrid Developer Experience Engineer
@SendGrid

**Comment by artiemq** [comment]
Those tests failed.
https://github.com/sendgrid/sendgrid-python/blob/a403813a9f4e95f8695b9a4a547dfbcedccc8671/test/test_project.py#L10-L20
Looks like `docker-compose.yml`, `env_sample` are absent in master and `./docker/Dockerfile ` not a directory. 

I think it would be better to comment failed tests if you want to use them later.

**Comment by mbernier** [comment]
Those file tests failing is expected behavior, because we have PRs coming that will resolve them.

Thanks so much for following up! 

Please do grab a time on my calendar (see previous comment)

Thanks!!

**Comment by thinkingserious** [comment]
Hello @artiemq,<br /><br/>Thanks again for the PR!<br />                                              <br />We appreciate your contribution and look forward to                                              continued collaboration. Thanks!                                             <br /><br />Team SendGrid DX

**Pull request merged**
