### PR TITLE
docs: Fix grammatical errors

### PR DESCRIPTION
**Pull request by vinayak42**
# Fixes # 

### Checklist
- [x] I have made a material change to the repo (functionality, testing, spelling, grammar)
- [x] I have read the [Contribution Guide] and my PR follows them.
- [x] I updated my branch with the master branch.
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation about the functionality in the appropriate .md file
- [ ] I have added in line documentation to the code I modified

### Short description of what this PR does:
- Fix grammatical errors in comments

If you have questions, please send an email to [SendGrid](mailto:dx@sendgrid.com), or file a GitHub Issue in this repository.

### CODE REVIEW

**Comment by vinayak42** [comment]
@thinkingserious @misterdorm Apologies for the inconvenience. I am having some issues about rebasing this to v4. Could you trace the exact steps/commands to do the same in GitHub?

**Comment by misterdorm** [comment]
@vinayak42 It's probably easiest to start with a new branch, branched from v4, and then merge/apply your commits onto that branch. And then force push to this PR.

**Comment by vinayak42** [comment]
@misterdorm Thanks for the info. 
On a side note, I noticed that my username no longer appears on the SendGrid Leaderboard, as it used to, a few days ago. Kindly look into the matter. Thanks

**Comment by misterdorm** [comment]
I know that they are still tabulating the final scores, etc., so there may be some inaccuracies on that page.

**Comment by thinkingserious** [comment]
Hello @vinayak42,

Do you mind re-submitting this PR against the v4 branch?

Thanks!

Elmer

**Pull request merged**
