### PR TITLE
refactor personalization.py as in issue #501

### LINKED ISSUE #501: Fix "similar-code" issue in sendgrid/helpers/mail/personalization.py
Similar blocks of code found in 3 locations. Consider refactoring.

https://codeclimate.com/github/sendgrid/sendgrid-python/sendgrid/helpers/mail/personalization.py#issue_59f639d0343eae000100009f

### PR DESCRIPTION
**Pull request by defaults**
reduce Cognitive Complexity of get method and refactor init and other methods of personalization class

# Fixes #501 

### Checklist
- [x] I have made a material change to the repo (functionality, testing, spelling, grammar)
- [x] I have read the [Contribution Guide] and my PR follows them.
- [x] I updated my branch with the master branch.
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation about the functionality in the appropriate .md file
- [x] I have added inline documentation to the code I modified

### Short description of what this PR does:
- Reduce Cognitive Complexity of `get` method
- Refactor to remove similar code block at many places

If you have questions, please send an email to [Sendgrid](mailto:dx@sendgrid.com), or file a Github Issue in this repository.

### CODE REVIEW

**Comment by codervikash** [comment]
@thinkingserious hey, all checks passed! can you please code review and suggest changes if any and merge if everything ok? Thanks.

**Comment by codervikash** [comment]
@thinkingserious @mbernier hey, all checks passed! can you please code review and suggest changes if any and merge if everything ok? Thanks.

**Comment by codervikash** [comment]
@thinkingserious @mbernier hey, all checks passed! can you please code review and suggest changes if any and merge if everything ok? Thanks.

**Comment by codervikash** [comment]
@thinkingserious @mbernier hey, this PR is open for around a day. Can we do code review and merge the changes. Being my first open source contribution to a popular repo used by many, I am a bit excited to see it merged.

**Comment by codervikash** [comment]
@thinkingserious @mbernier do you guys really want people to contribute to your repo? I have this Pr for two days and have pinged multiple times on issue and PR to code review or merge and I see no reply but other PRs are being merged. Don't you guys have the courtesy to reply at least? 

People like you and these shitty repos demotivate open source contributors. Don't be an ass! Do hell with your hacktoberfest.

**Comment by codervikash** [comment]
@thinkingserious please at least close the repo if not needed!

**Comment by mbernier** [comment]
"@codervikash

We have not been able to merge your Pull Request, but because you are awesome - we wanted to make sure you could still get a SendGrid Hacktoberfest shirt.  

Please go **fill [out our swag form](https://dx.sendgrid.com/swag) before Nov 5th** and we will send the shirt! (We know that you might have tried this before and it didn’t work, sorry about that!)

### **You have till Nov 5th to fill out this form** in order to get the Hacktoberfest shirt!

Thank you for contributing during Hacktoberfest! We hope to see you in the repos soon! Just so you know, we always give away a SendGrid shirt for your first ever non-Hacktoberfest PR that gets merged."

**Comment by codervikash** [comment]
@mbernier Hey, thanks and sorry for being rude! I was overexcited to see my first contribution to a well known and used repo merged. Leaving aside t-shirt, I would like to get this merged. Please do a code review whenever free and suggest changes. Travis is falling after back-merge, due to some issue in master. I will try fixing that also. Thanks for the response.

**Comment by mbernier** [comment]
No worries @codervikash! We appreciate your excitement and hope that you keep an eye on our repos going forward!

**Comment by thinkingserious** [comment]
Thanks again for helping improve this SDK! 

We have started to execute on PR #347 (Python Mail Helper Refactor) and have integrated your work into [this branch](https://github.com/sendgrid/sendgrid-python/tree/v4). Please follow along at PR #347 to follow our progress.

With Best Regards,

Elmer

**Pull request closed without merging**
