### PR TITLE
Separate Attribution links in CoC #671

### PR DESCRIPTION
**Pull request by Skchoudhary**
Signed-off-by: Skchoudhary <choudharysaab786@gmail.com>

# Fixes # 671

### Checklist
- [ ] I have made a material change to the repo (functionality, testing, spelling, grammar)
- [X] I have read the [Contribution Guide] and my PR follows them.
- [X] I updated my branch with the master branch.
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation about the functionality in the appropriate .md file
- [ ] I have added in line documentation to the code I modified

### Short description of what this PR does:
- separate the link for Open Source Initiative General Code of Conduct and Apache Code of Conduct to appear on the different line.
- 

If you have questions, please send an email to [SendGrid](mailto:dx@sendgrid.com), or file a GitHub Issue in this repository.

### CODE REVIEW

**Comment by SendGridDX** [comment]
[CLA assistant check](https://cla.sendgrid.com/sendgrid/sendgrid-python?pullRequest=679) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.sendgrid.com/sendgrid/sendgrid-python?pullRequest=679) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.sendgrid.com/check/sendgrid/sendgrid-python?pullRequest=679) it.</sub>

**Comment by thinkingserious** [comment]
Hello @Skchoudhary,<br /><br/>Thanks again for the PR!<br />                                              <br />It's <a href="https://sendgrid.com/blog/hacktoberfest-2018-has-arrived/">HACKTOBERFEST</a>! We want to show our appreciation by sending                                              you some special Hacktoberfest swag. If you have not already, could you please fill out                                              <a href="https://dx.sendgrid.com/hacktoberfest/join">this form</a> so we can send it to you? Thanks!                                             <br /><br />Team SendGrid DX

**Comment by thinkingserious** [comment]
Hello @Skchoudhary,

Could you please merge this against our [v4 branch](https://github.com/sendgrid/sendgrid-python/tree/v4)? Thank you!

With Best Regards,

Elmer

**Comment by Skchoudhary** [comment]
Hi @thinkingserious 
Let me know that If I have done the merge right or not.

**Comment by thinkingserious** [comment]
Hello @Skchoudhary,<br /><br/>Thanks again for the PR!<br /><br />                                         We noticed that you have earned 1 out of the 5 points needed to receive glorious SendGrid Hacktoberfest swag.<br /><br />                                         Please take a moment to checkout <a href="https://dx.sendgrid.com/hacktoberfest/issues">this link</a> to find more issues to get you past the required threshold.<br /><br />                                         Also, please be sure that you have officially registered <a href="https://dx.sendgrid.com/hacktoberfest/join">here</a>.<br /><br />                                         Thank you and Happy Hacktobering!<br /><br />                                         Team SendGrid DX

**Comment by Skchoudhary** [comment]
Hi @misterdorm 
I have follow these steps for re-base, let me know if I am doing it wrong.
```
1. git rebase --hard <my commit hash>
2. git rebase upstream/v4
3. After that git add and git rebase --continue.
```

**Comment by misterdorm** [comment]
I think you are going to have to start with a clean branch with only your changes.  Rebasing back to v4 after you've already merged in everything from master is still going to include all the master commits.

**Comment by Skchoudhary** [comment]
@misterdorm  ok, Will open a new pull request.

**Pull request closed without merging**
