### PR TITLE
Add a tutorial to deploy a simple "Hello Email" app on Heroku

### PR DESCRIPTION
**Pull request by swapagarwal**
See #356

### CODE REVIEW

**Comment by SendGridDX** [comment]
[CLA assistant check](https://cla.sendgrid.com/sendgrid/sendgrid-python?pullRequest=443) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.sendgrid.com/sendgrid/sendgrid-python?pullRequest=443) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.sendgrid.com/check/sendgrid/sendgrid-python?pullRequest=443) it.</sub>

**Comment by swapagarwal** [comment]
ping

**Comment by swapagarwal** [comment]
ping

**Comment by swapagarwal** [comment]
Not sure why travis is failing.

**Comment by mbernier** [comment]
Travis is failing due to an unrelated issue and I believe that it is fixed in another PR - so we're not worried about it :)

---

@swapagarwal

We have not been able to merge your Pull Request, but because you are awesome - we wanted to make sure you could still get a SendGrid Hacktoberfest shirt.  

Please go **fill [out our swag form](https://dx.sendgrid.com/swag) before Nov 5th** and we will send the shirt! (We know that you might have tried this before and it didn’t work, sorry about that!)

### **You have till Nov 5th to fill out this form** in order to get the Hacktoberfest shirt!

Thank you for contributing during Hacktoberfest! We hope to see you in the repos soon! Just so you know, we always give away a SendGrid shirt for your first ever non-Hacktoberfest PR that gets merged.

**Comment by swapagarwal** [comment]
I rebased it on master, but travis is still failing. 🤔

**Comment by swapagarwal** [comment]
ping

**Comment by swapagarwal** [comment]
ping

**Comment by thinkingserious** [comment]
Hello @swapagarwal,

Your PR is currently on our list for review. We are processing them from oldest to newest. Unfortunately, this is taking much longer than usual due to the amazing results of Hacktoberfest. We appreciate your patience, thanks!

With Best Regards,

Elmer

**Comment by thinkingserious** [comment]
Hello @swapagarwal,<br /><br/>Thanks again for the PR!<br />                                              <br />We appreciate your contribution and look forward to                                              continued collaboration. Thanks!                                             <br /><br />Team SendGrid DX

**Pull request merged**
