### PR TITLE
Updated date-range in LICENSE file 

### LINKED ISSUE #491: Date range is incorrect in Licence file.
#### Issue Summary

The [license](https://github.com/sendgrid/sendgrid-python/blob/master/LICENSE.txt) file contains old year range. It must be updated.

### PR DESCRIPTION
**Pull request by dhruvhacks**
# Fixes # 
This PR fixes #491 

### Checklist
- [ ] Update date-range in License file

### Short description of what this PR does:
The date-range mentioned in LICENSE file is outdated, this PR updates the date-range of [license](https://github.com/sendgrid/sendgrid-python/blob/master/LICENSE.txt) file.

### CODE REVIEW

**Comment by SendGridDX** [comment]
[CLA assistant check](https://cla.sendgrid.com/sendgrid/sendgrid-python?pullRequest=492) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.sendgrid.com/sendgrid/sendgrid-python?pullRequest=492) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.sendgrid.com/check/sendgrid/sendgrid-python?pullRequest=492) it.</sub>

**Comment by thinkingserious** [comment]
Hello @dhruvhacks,<br /><br/>Thanks again for the PR!<br />                                              <br />We want to show our appreciation by sending                                              you some swag. Could you please fill out                                              <a href="https://dx.sendgrid.com/swag">this form</a> so we can send it to you? Thanks!                                             <br /><br />Team SendGrid DX

**Comment by dhruvhacks** [comment]
@thinkingserious Thank you very much for this link! :smile:

**Comment by mbernier** [comment]
@dhruvhacks 
If you are interested, we would love the opportunity to talk to you about Hacktoberfest and our API libraries.

Our agenda would be: Explore what you liked and is there anything we can do to improve? 

You can grab a time [on my calendar](https://calendly.com/matt-bernier/hacktoberfest-follow-up) that works for you and we can have a chat on Google Hangout or Skype. If you prefer, you can email me using my GitHub username at my company’s domain.

Thank you so much,

Matt Bernier - @mbernier - SendGrid Developer Experience Product Manager
Elmer Thomas - @thinkingserious - SendGrid Developer Experience Engineer
@SendGrid

**Pull request merged**
