### PR TITLE
Added PULL_REQUEST_TEMPLATE

### PR DESCRIPTION
**Pull request by dhruvramdev**
#445 
Added a PULL_REQUEST_TEMPLATE.

- [x] I have read the SendGrid Contributor License Agreement (CLA)
- [x] I have read the [Contribution Guide] and my PR follows them.
- [x] My branch is up-to-date with the master branch.
- [x] I have added necessary documentation.

### CODE REVIEW

**Comment by SendGridDX** [comment]
[CLA assistant check](https://cla.sendgrid.com/sendgrid/sendgrid-python?pullRequest=453) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.sendgrid.com/sendgrid/sendgrid-python?pullRequest=453) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.sendgrid.com/check/sendgrid/sendgrid-python?pullRequest=453) it.</sub>

**Comment by thinkingserious** [comment]
Hello @dhruvramdev,<br /><br/>Thanks again for the PR!<br />                                              <br />We want to show our appreciation by sending                                              you some swag. Could you please fill out                                              <a href="https://dx.sendgrid.com/swag">this form</a> so we can send it to you? Thanks!                                             <br /><br />Team SendGrid DX

**Comment by dhruvramdev** [comment]
@thinkingserious Thanks for Merging and Swag.

**Comment by mbernier** [comment]
@dhruvramdev 
If you are interested, we would love the opportunity to talk to you about Hacktoberfest and our API libraries.

Our agenda would be: Explore what you liked and is there anything we can do to improve? 

You can grab a time [on my calendar](https://calendly.com/matt-bernier/hacktoberfest-follow-up) that works for you and we can have a chat on Google Hangout or Skype. If you prefer, you can email me using my GitHub username at my company’s domain.

Thank you so much,

Matt Bernier - @mbernier - SendGrid Developer Experience Product Manager
Elmer Thomas - @thinkingserious - SendGrid Developer Experience Engineer
@SendGrid

**Comment by thinkingserious** [comment]
Duplicate of #446

**Pull request merged**
