### PR TITLE
Fixed a broken link for use cases

### PR DESCRIPTION
**Pull request by shendrekbharath**
# Fixes 

### Checklist
- [ ] I have made a material change to the repo (functionality, testing, spelling, grammar)
- [ ] I have read the [Contribution Guide] and my PR follows them.
- [ ] I updated my branch with the master branch.
- [ ] I have added tests that prove my fix is effective or that my feature works
- [#] I have added necessary documentation about the functionality in the appropriate .md file
- [ ] I have added in line documentation to the code I modified

### Short description of what this PR does:
The below USE_CASES link under Changelog.md was broken, fixed the same.

Error: https://github.com/sendgrid/sendgrid-python/blob/master/USE_CASES.md on line 228 is unreachable.

Updated Link
https://github.com/sendgrid/sendgrid-python/tree/master/use_cases

If you have questions, please send an email to [SendGrid](mailto:dx@sendgrid.com), or file a GitHub Issue in this repository.

### CODE REVIEW

**Comment by SendGridDX** [comment]
[CLA assistant check](https://cla.sendgrid.com/sendgrid/sendgrid-python?pullRequest=703) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.sendgrid.com/sendgrid/sendgrid-python?pullRequest=703) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.sendgrid.com/check/sendgrid/sendgrid-python?pullRequest=703) it.</sub>

**Comment by thinkingserious** [comment]
Hello @shendrekbharath,<br /><br/>Thanks again for the PR!<br />                                              <br />It's <a href="https://sendgrid.com/blog/hacktoberfest-2018-has-arrived/">HACKTOBERFEST</a>! We want to show our appreciation by sending                                              you some special Hacktoberfest swag. If you have not already, could you please fill out                                              <a href="https://dx.sendgrid.com/hacktoberfest/join">this form</a> so we can send it to you? Thanks!                                             <br /><br />Team SendGrid DX

**Comment by misterdorm** [comment]
@shendrekbharath  Sorry.  We'll need the PR to be against the `v4` branch, not `master`.  You can close this PR and create a new one if that's easier than rebasing.  Thanks!

**Comment by thinkingserious** [comment]
Hello @shendrekbharath,

Are you still interested in submitting this one? If so, please rebase against the v4 branch or please create a new PR against the v4 branch.

Thanks!

With Best Regards,

Elmer

**Comment by shendrekbharath** [comment]
Hi Elmer,
Thanks for reminding me on this!

I have created a new PR for v4 branch.

https://github.com/sendgrid/sendgrid-python/pull/754

Rgrds,
Bharath

**Comment by thinkingserious** [comment]
Perfect, thank you!

**Pull request closed without merging**
