### PR TITLE
refactor helpers using property getter/setter

### PR DESCRIPTION
**Pull request by denis90**
sendgrid/sendgrid-python#207

### CODE REVIEW

**Comment by SendGridDX** [comment]
Hello @denis90,

This one finally bubbled up to the top of our queue. I see there are few conflicts, could you please resolve them?

Thanks!

Elmer

**Comment by SendGridDX** [comment]
[CLA assistant check](https://cla.sendgrid.com/sendgrid/sendgrid-python?pullRequest=244) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.sendgrid.com/sendgrid/sendgrid-python?pullRequest=244) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.sendgrid.com/check/sendgrid/sendgrid-python?pullRequest=244) it.</sub>

**Comment by denis90** [comment]
resolved conflicts

**Comment by SendGridDX** [comment]
Hello @denis90,<br /><br/>Thanks again for the PR!<br />                                              <br />We want to show our appreciation by sending                                              you some swag. Could you please fill out                                              <a href="https://dx.sendgrid.com/swag">this form</a> so we can send it to you? Thanks!                                             <br /><br />Team SendGrid DX

**Pull request merged**
