### PR TITLE
Update USE_CASES.md - Google App Engine Tutorial

### LINKED ISSUE #359: Create a tutorial to deploy a simple Hello Email app on Google App Engine with Python using this SDK
Create a tutorial that explains how to create a simple Hello Email app and [deploy to Google App Engine](https://cloud.google.com/).

The example should utilize best practices for storing credentials. By the end of the tutorial, the user should be able to send an email using their deployed app.

Please add the tutorial to USE_CASES.md.

### PR DESCRIPTION
**Pull request by Xndr7**
Closes #359.

Please check and inform me if any changes have to be made as I am new here and this is my first PR.

Thanks!

### CODE REVIEW

**Comment by SendGridDX** [comment]
[CLA assistant check](https://cla.sendgrid.com/sendgrid/sendgrid-python?pullRequest=437) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.sendgrid.com/sendgrid/sendgrid-python?pullRequest=437) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.sendgrid.com/check/sendgrid/sendgrid-python?pullRequest=437) it.</sub>

**Comment by mbernier** [comment]
It all looks good, we will test it and get it merged!

**Comment by mbernier** [comment]
@Xndr7

We have not been able to merge your Pull Request, but because you are awesome - we wanted to make sure you could still get a SendGrid Hacktoberfest shirt.  

Please go **fill [out our swag form](https://dx.sendgrid.com/swag) before Nov 5th** and we will send the shirt! (We know that you might have tried this before and it didn’t work, sorry about that!)

### **You have till Nov 5th to fill out this form** in order to get the Hacktoberfest shirt!

Thank you for contributing during Hacktoberfest! We hope to see you in the repos soon! Just so you know, we always give away a SendGrid shirt for your first ever non-Hacktoberfest PR that gets merged.

**Comment by thinkingserious** [comment]
Hello @Xndr7,

I will check with our vendor on the status of your swag. Thanks for letting us know!

With Best Regards,

Elmer

**Comment by Xndr7** [comment]
Hi @thinkingserious, 
If you could let me know asap it'll be much appreciated! 
I haven't received it yet as well as no communication regarding any package. 
I'm still waiting! :|
Please do the needful at the earliest! 
Thanks! 👍

**Comment by thinkingserious** [comment]
Hello @Xndr7,

We have found that shipments to certain countries take longer than usual. Our provider believes that the shipments will all be delivered by the end of the month.

With Best Regards,

Elmer

**Comment by Xndr7** [comment]
Hi! 
I still haven't received the package.
If possible, please check the status of the package. 
I have been waiting for it eagerly for so long! 
@thinkingserious if you could help me out please. 
Thanks guys and sorry for the inconvenience.

**Comment by thinkingserious** [comment]
Hello @Xndr7,

The packages are still being shipped and delivered. Once our vendor has told us they are all delivered, and you still have not received your swag, I'll be happy to help figure out the issue.

Thanks and sorry for the long wait!

With Best Regards,

Elmer

**Comment by Xndr7** [comment]
Hi, I still haven't received it. I was busy for the past few months and as a result, had forgotten about it. Sorry for that. Please if you could tell me the status of what's happening. Again, @thinkingserious maybe you could shed some light on this?
Thanks, 
Sanjiv.

**Comment by thinkingserious** [comment]
Hello @Xndr7,

Could you please email me at dx@sendgrid.com with your mailing information? Please reference this thread in your email.

Thanks!

With Best Regards,

Elmer

**Comment by af4ro** [comment]
Hey @Xndr7,
Could you please resolve the merge conflicts so that we can attempt to merge this into our latest update!

Thank you for your time and contribution!

**Comment by thinkingserious** [comment]
@af4ro,

Besides the merge conflict, was the tutorial good to go?

**Comment by af4ro** [comment]
@thinkingserious the steps are accurate and good to go. 
I'll fix the merge conflict and push another commit.

**Comment by thinkingserious** [comment]
@Xndr7,

Could you please resolve the merge conflicts? Thank you!

With Best Regards,

Elmer

**Comment by thinkingserious** [comment]
Hello @Xndr7,

I'm ready to merge this one, could you please resolve the merge conflicts? Thank you!

With Best Regards,

Elmer

**Comment by childish-sambino** [comment]
Closing as there's been no progress to rebase this change.

**Pull request closed without merging**
