### PR TITLE
Update CONTRIBUTING - contribution guideline to branch off development

### LINKED ISSUE #675: Document new Git workflow in CHANGELOG.md
#### Issue Summary

We want to update our git workflow to function more like [Gitflow](https://www.atlassian.com/git/tutorials/comparing-workflows/gitflow-workflow). We need to update the CONTRIBUTING.md file and PULL_REQUEST_TEMPLATE to direct contributors to fork/branch off the `development` branch and to merge their PRs with the `development` branch. Once this issue is complete, we will be creating the `development` branch and making that branch the default. This is part of a larger strategy to execute releases for this SDK on a predictable cadence.

#### Acceptance Criteria

* Update CONTRIBUTING.md documentation, explaining the process of forking and branching off the `development` branch and submitting PRs agains the `development` branch.
* Update PULL_REQUEST_TEMPLATE with the same addition to the CONTRIBUTING.md documentation.

### PR DESCRIPTION
**Pull request by myzeprog**
# Fixes #675 

### Checklist
- [ ] I have made a material change to the repo (functionality, testing, spelling, grammar)
- [ ] I have read the [Contribution Guide] and my PR follows them.
- [ ] I updated my branch with the master branch.
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation about the functionality in the appropriate .md file
- [ ] I have added in line documentation to the code I modified

### Short description of what this PR does:
- Update CONTRIBUTING - contribution guideline to branch off development

If you have questions, please send an email to [SendGrid](mailto:dx@sendgrid.com), or file a GitHub Issue in this repository.

### CODE REVIEW

**Comment by thinkingserious** [comment]
Hello @myzeprog,<br /><br/>Thanks again for the PR!<br />                                              <br />It's <a href="https://sendgrid.com/blog/hacktoberfest-2018-has-arrived/">HACKTOBERFEST</a>! We want to show our appreciation by sending                                              you some special Hacktoberfest swag. If you have not already, could you please fill out                                              <a href="https://dx.sendgrid.com/hacktoberfest/join">this form</a> so we can send it to you? Thanks!                                             <br /><br />Team SendGrid DX

**Comment by thinkingserious** [comment]
Hello @myzeprog,

Could you please merge this against our [v4 branch](https://github.com/sendgrid/sendgrid-python/tree/v4)? Thank you!

With Best Regards,

Elmer

**Comment by thinkingserious** [comment]
Hello @myzeprog,<br /><br/>Thanks again for the PR!<br /><br />                                         You have earned 11 out of the 5 points needed to receive glorious SendGrid Hacktoberfest swag.<br /><br />                                         Please take a moment to checkout <a href="https://dx.sendgrid.com/hacktoberfest/issues">this link</a> to find more issues to get you past the required threshold or to simply continue the celebration.<br /><br />                                         Also, <strong>please be sure you have officially registered with us <a href="https://dx.sendgrid.com/hacktoberfest/join">here</a> by November 1, 2018</strong> to qualify.<br /><br />                                         If you have any questions you can email us at <a href="mailto:dx+hacktoberfest2018@sendgrid.com">dx+hacktoberfest2018@sendgrid.com</a>.<br /><br />                                         Thank you and Happy Hacktobering!<br /><br />                                         Team SendGrid

**Comment by myzeprog** [comment]
Please see #730 as a replacement on the v4 branch.

**Pull request closed without merging**
