### PR TITLE
Fix #426: Attempt to sync before executing shell command

### LINKED ISSUE #426: Repair Docker Build
Please see: https://hub.docker.com/r/sendgrid/sendgrid-python/builds/bzvwzufztt652fqrebrxfgq

### PR DESCRIPTION
**Pull request by narayanaditya95**
Fix #426: Attempt to sync before executing shell command

### CODE REVIEW

**Comment by SendGridDX** [comment]
[CLA assistant check](https://cla.sendgrid.com/sendgrid/sendgrid-python?pullRequest=430) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.sendgrid.com/sendgrid/sendgrid-python?pullRequest=430) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.sendgrid.com/check/sendgrid/sendgrid-python?pullRequest=430) it.</sub>

**Comment by narayanaditya95** [comment]
Please find the [succeeding Docker build](https://hub.docker.com/r/narayanaditya95/sendgrid-python/builds/begufmhtmrkrkfeuyyko5un/)

**Comment by gabrielkrell** [comment]
Good fix to a strange bug.  For posterity, [here's](https://github.com/moby/moby/issues/9547) a big thread where people seem to have discovered it and a few workarounds.

**Comment by mbernier** [comment]
Nice work @narayanaditya95 and thank you for the docs lead @gabrielkrell 

For Posterity: WHAT A WEIRD FREAKING BUG.

**Comment by thinkingserious** [comment]
Hello @narayanaditya95,<br /><br/>Thanks again for the PR!<br />                                              <br />We want to show our appreciation by sending                                              you some swag. Could you please fill out                                              <a href="https://dx.sendgrid.com/swag">this form</a> so we can send it to you? Thanks!                                             <br /><br />Team SendGrid DX

**Pull request merged**
