### PR TITLE
Conformance to style standards

### LINKED ISSUE #632: Require conformance to style standards
#### Issue Summary

In the `CONTRIBUTING.md` file there is a section on Style Guidelines & Naming Conventions. Please review and implement a check in Travis CI. If there are any style errors, either fix or create a rule to exclude the error.

Before writing any code, we suggest you review our `CONTRIBUTING.md` file and propose your solution for discussion here in the comments. Thank you!

#### Aceptance Criteria

* TravisCI checks that the code conforms to our Style Guidelines & Naming Conventions as defined in our `CONTRIBUTING.md` file
* tests pass locally, in Travis CI and using Docker

### PR DESCRIPTION
**Pull request by moshemeirelles**
# Fixes #632 

### Checklist
- [X] I have made a material change to the repo (functionality, testing, spelling, grammar)
- [X] I have read the [Contribution Guide] and my PR follows them.
- [X] I updated my branch with the master branch.
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation about the functionality in the appropriate .md file
- [ ] I have added in line documentation to the code I modified

### Short description of what this PR does:
- update .travis.yml to verify PEP8 errors
- made changes in files as suggested by pycodestyle following PEP8 code compliance
```
├── register.py
├── setup.py
├── examples
│   ├── campaigns
│   │   └── campaigns.py
│   ├── categories
│   │   └── categories.py
│   ├── helpers
│   │   ├── mail_example.py
│   │   └── stats
│   │       └── stats_example.py
│   └── mail
│       └── mail.py
├── sendgrid
│   ├── sendgrid.py
│   └── helpers
│       ├── endpoints
│       │   └── ip
│       │      └── unassigned.py
│       ├── inbound
│       │   ├── app.py
│       │   ├── config.py
│       │   └── send.py
│       └── mail
│           ├── content.py
│           ├── exceptions.py
│           ├── mail.py
│           ├── personalization.py
│           ├── subscription_tracking.py
│           ├── tracking_settings.py
│           └── validators.py
├── sendgrid
│   ├── test_app.py
│   ├── test_mail.py
│   ├── test_project.py
│   ├── test_sendgrid.py
│   ├── test_stats.py
│   └── test_unassigned.py
```

If you have questions, please send an email to [SendGrid](mailto:dx@sendgrid.com), or file a GitHub Issue in this repository.

### CODE REVIEW

**Comment by SendGridDX** [comment]
[CLA assistant check](https://cla.sendgrid.com/sendgrid/sendgrid-python?pullRequest=654) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.sendgrid.com/sendgrid/sendgrid-python?pullRequest=654) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.sendgrid.com/check/sendgrid/sendgrid-python?pullRequest=654) it.</sub>

**Comment by hugovk** [comment]
In .travis.yml:

```yml
# errors W605 and W504 added to avoid inconsistent errors happening
# error W605 happening on validators.py:28:40 on a valid Regex
# error W504 happening on validators.py:54:29 on a valid line break operator
- pycodestyle --ignore=W605,W504 --exclude='build'
```

W605: The regex isn't quite valid, see https://github.com/sendgrid/sendgrid-python/pull/698 for a fix. Once that is merged, you should remove the W605 exception.

---

As a general point, it might be better to avoid global exceptions as that means all the other code is excluded. Instead, you can skip checking single lines like this:

```python
regex = "\."  # noqa
```

Or better, skip checking only a single error type:

```python
regex = "\."  # noqa: W605
```

**Comment by thinkingserious** [comment]
Hello @moshemeirelles,<br /><br/>Thanks again for the PR!<br />                                              <br />It's <a href="https://sendgrid.com/blog/hacktoberfest-2018-has-arrived/">HACKTOBERFEST</a>! We want to show our appreciation by sending                                              you some special Hacktoberfest swag. If you have not already, could you please fill out                                              <a href="https://dx.sendgrid.com/hacktoberfest/join">this form</a> so we can send it to you? Thanks!                                             <br /><br />Team SendGrid DX

**Comment by thinkingserious** [comment]
Hello @moshemeirelles,

Could you please merge this against our v4 branch? Thank you!

With Best Regards,

Elmer

**Pull request closed without merging**
