### PR TITLE
add AWS app tutorial to USE_CASES.md

### PR DESCRIPTION
**Pull request by codevbus**
Added tutorial to USE_CASES.md for AWS, utilizing the AWS CodeStar service.

### CODE REVIEW

**Comment by SendGridDX** [comment]
[CLA assistant check](https://cla.sendgrid.com/sendgrid/sendgrid-python?pullRequest=366) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.sendgrid.com/sendgrid/sendgrid-python?pullRequest=366) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.sendgrid.com/check/sendgrid/sendgrid-python?pullRequest=366) it.</sub>

**Comment by thinkingserious** [comment]
Hi @codevbus,

Could you please resolve the conflict? Thanks!

**Comment by thinkingserious** [comment]
Hi @codevbus,

Could you please resolve the conflict? Thanks!

**Comment by codevbus** [comment]
@thinkingserious The conflict was corrected in 87e84b7, however it now looks like it's in conflict again?

**Comment by thinkingserious** [comment]
@codevbus

We have not been able to merge your Pull Request, but because you are awesome - we wanted to make sure you could still get a SendGrid Hacktoberfest shirt.  

Please go **fill [out our swag form](https://dx.sendgrid.com/swag) before Nov 5th** and we will send the shirt! (We know that you might have tried this before and it didn’t work, sorry about that!)

### **You have till Nov 5th to fill out this form** in order to get the Hacktoberfest shirt!

Thank you for contributing during Hacktoberfest! We hope to see you in the repos soon! Just so you know, we always give away a SendGrid shirt for your first ever non-Hacktoberfest PR that gets merged.

**Comment by codevbus** [comment]
@thinkingserious - Thanks for the offer! Luckily, I was already sent my shirt/swag.

Several times now I've been asked to correct merge conflicts so that my PR can be merged in, then nothing happens and another PR is merged ahead of mine, creating a new conflict.

What is the path forward at this point?

**Comment by thinkingserious** [comment]
Hi @codevbus,

I apologize for the conflict mess :(

In my rush to merge small items as they came in, I failed to realize the impact on previous open PRs. So now, we are processing all the PRs in order from oldest to newest. Since we received over 1,000 PRs last month, this is taking longer than normal.

It should be safe for you to go ahead fix the current conflicts.

We appreciate your patience and support!

With Best Regards,

Elmer

**Comment by codevbus** [comment]
@thinkingserious - Corrected the conflicts in 36e68ba.

No worries, and thanks for your help/responses!

Also, FWIW, the link you sent for the shirt did not work. I attempted it after realizing you were referring to a SendGrid shirt specifically, not the general Hacktoberfest one.

Thanks again, enjoy your weekend!

**Comment by thinkingserious** [comment]
@codevbus,

Sorry about that! The link should now work :)

**Comment by thinkingserious** [comment]
Hello @codevbus,<br /><br/>Thanks again for the PR!<br />                                              <br />We appreciate your contribution and look forward to                                              continued collaboration. Thanks!                                             <br /><br />Team SendGrid DX

**Pull request merged**
