### PR TITLE
Update attachment helper to accept files

### LINKED ISSUE #394: Attachment helper for base64 encoding
We have an example in USE_CASES.md on how to handle attachments. 

We need to update the `Attachment` object such that it can also take in a raw file, rather than a base64 encoded file, and perform the base64 encoding behind the scenes. 

Note that the total size of your email, including attachments, must be less than 30MB. The total size is calculated from the entire JSON payload. Note that you will need to handle the case where UTF-8 characters are included.

### PR DESCRIPTION
**Pull request by dzeban**
Attachment helper now can accept filenames and file objects via `file`
property. It will do the following:

* open the file in binary mode
* read it
* do the base64 encoding and set it to `content` attribute
* detect MIME type and set it to `type` attribute
* set filename to `filename` attribute

All attributes may be overriden.

Here is an example:

    attachment1 = Attachment()
    attachment1.file = "file.pdf"
    attachment1.filename = "overriden_name.pdf"

    attachment2 = Attachment()
    with open("file.pdf") as f:
        attachment2.file = f
    attachment2.type = "application/json"

Fixes #394.

### CODE REVIEW

**Comment by SendGridDX** [comment]
[CLA assistant check](https://cla.sendgrid.com/sendgrid/sendgrid-python?pullRequest=399) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.sendgrid.com/sendgrid/sendgrid-python?pullRequest=399) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.sendgrid.com/check/sendgrid/sendgrid-python?pullRequest=399) it.</sub>

**Comment by dzeban** [comment]
This works for both Python 2 and Python 3, which unfortunately requires Python version checking.
Also, I'm not sure about using `@property` for `file`. This attribute doesn't have getter, because we close the file asap. We do this because there is no destructor in any sense and I wanted to keep API the same.

**Comment by thinkingserious** [comment]
@dzeban

We have not been able to merge your Pull Request, but because you are awesome - we wanted to make sure you could still get a SendGrid Hacktoberfest shirt.  

Please go **fill [out our swag form](https://dx.sendgrid.com/swag) before Nov 5th** and we will send the shirt! (We know that you might have tried this before and it didn’t work, sorry about that!)

### **You have till Nov 5th to fill out this form** in order to get the Hacktoberfest shirt!

Thank you for contributing during Hacktoberfest! We hope to see you in the repos soon! Just so you know, we always give away a SendGrid shirt for your first ever non-Hacktoberfest PR that gets merged.

**Comment by thinkingserious** [comment]
Hello @dzeban,

Would you mind rebasing and updating your PR? The Attachment object now lives in its own file.

Thanks!

With Best Regards,

Elmer

**Comment by dzeban** [comment]
Ok, I'll update it in a few days.

**Comment by thinkingserious** [comment]
Thanks @dzeban!

**Comment by childish-sambino** [comment]
Closing as there's been no progress in rebasing.

**Pull request closed without merging**
