### PR TITLE
upgraded requirements.txt versions

### LINKED ISSUE #623: Upgrade versions of requirements in requirements.txt
#### Issue Summary

Update the version numbers of the requirements in requirements.txt as currently we have versions above the current mentioned ones that are stable.

#### Steps to Reproduce

1. Check requirements.txt

It's better to stay up to date with these as it would help us avoid problems later. 
I'd like to work on this.

### PR DESCRIPTION
**Pull request by rahulkumaran**
# Fixes #623 

### Checklist
- [x] I have read the [Contribution Guide] and my PR follows them.
- [x] I updated my branch with the master branch.
- [x] I have added necessary documentation about the functionality in the appropriate .md file

### Short description of what this PR does:
- This PR upgrades the versions in requirements.txt
- The latest stable versions now exists there.

If you have questions, please send an email to [SendGrid](mailto:dx@sendgrid.com), or file a GitHub Issue in this repository.

### CODE REVIEW

**Comment by SendGridDX** [comment]
[CLA assistant check](https://cla.sendgrid.com/sendgrid/sendgrid-python?pullRequest=624) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.sendgrid.com/sendgrid/sendgrid-python?pullRequest=624) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.sendgrid.com/check/sendgrid/sendgrid-python?pullRequest=624) it.</sub>

**Comment by rahulkumaran** [comment]
@thinkingserious could you please review this? Thanks! :smile:

**Comment by thinkingserious** [comment]
Hello @rahulkumaran,<br /><br/>Thanks again for the PR!<br />                                              <br />It's <a href="https://sendgrid.com/blog/hacktoberfest-2018-has-arrived/">HACKTOBERFEST</a>! We want to show our appreciation by sending                                              you some special Hacktoberfest swag. If you have not already, could you please fill out                                              <a href="https://dx.sendgrid.com/hacktoberfest/join">this form</a> so we can send it to you? Thanks!                                             <br /><br />Team SendGrid DX

**Comment by thinkingserious** [comment]
@rahulkumaran,

Could you please merge this into [this branch](https://github.com/sendgrid/sendgrid-python/tree/v4) instead? Thanks!

The python-http-client upgrade is a breaking change.

With Best Regards,

Elmer

**Comment by rahulkumaran** [comment]
@thinkingserious , sure! Will do that! There are a lot of conflicts arising currently when i try merging it into branch v4, so I'll send another PR for the same. Thanks!

**Pull request closed without merging**
