### PR TITLE
Update CONTRIBUTING.md to add python version 3.6

### LINKED ISSUE #657: Update CONTRIBUTING.md to add Python Version 3.6
#### Issue Summary

As contributor following listed steps on CONTRIBUTING.md, documentation doesn't bring the Python Version 3.6 on Initial Setup instructions to Test project. This version is declared on Tox commands, which causes an error when executed following initial setup steps.

#### Steps to Reproduce

1. Follow steps described in [Initial Setup](https://github.com/sendgrid/sendgrid-python/blob/master/CONTRIBUTING.md#initial-setup-1)

I'd would like to take this up.

### PR DESCRIPTION
**Pull request by moshemeirelles**
# Fixes #657 

### Checklist
- [X] I have made a material change to the repo (functionality, testing, spelling, grammar)
- [X] I have read the [Contribution Guide] and my PR follows them.
- [X] I updated my branch with the master branch.
- [ ] I have added tests that prove my fix is effective or that my feature works
- [X] I have added necessary documentation about the functionality in the appropriate .md file
- [ ] I have added in line documentation to the code I modified

### Short description of what this PR does:
- Update CONTRIBUTING.md to keep instructions updated according to commands to test project

If you have questions, please send an email to [SendGrid](mailto:dx@sendgrid.com), or file a GitHub Issue in this repository.

### CODE REVIEW

**Comment by thinkingserious** [comment]
Hello @moshemeirelles,<br /><br/>Thanks again for the PR!<br />                                              <br />It's <a href="https://sendgrid.com/blog/hacktoberfest-2018-has-arrived/">HACKTOBERFEST</a>! We want to show our appreciation by sending                                              you some special Hacktoberfest swag. If you have not already, could you please fill out                                              <a href="https://dx.sendgrid.com/hacktoberfest/join">this form</a> so we can send it to you? Thanks!                                             <br /><br />Team SendGrid DX

**Comment by thinkingserious** [comment]
Hello @moshemeirelles,

Could you please merge this against our [v4 branch](https://github.com/sendgrid/sendgrid-python/tree/v4)? Thank you!

With Best Regards,

Elmer

**Comment by thinkingserious** [comment]
Hello @moshemeirelles,<br /><br/>Thanks again for the PR!<br /><br />                                         We noticed that you have earned 4 out of the 5 points needed to receive glorious SendGrid Hacktoberfest swag.<br /><br />                                         Please take a moment to checkout <a href="https://dx.sendgrid.com/hacktoberfest/issues">this link</a> to find more issues to get you past the required threshold.<br /><br />                                         Also, please be sure that you have officially registered <a href="https://dx.sendgrid.com/hacktoberfest/join">here</a>.<br /><br />                                         Thank you and Happy Hacktobering!<br /><br />                                         Team SendGrid DX

**Comment by moshemeirelles** [comment]
Sure @thinkingserious ! I appreciate your attention :smile:

**Comment by moshemeirelles** [comment]
No special reason @hugovk I'll update to that

**Comment by hugovk** [comment]
3.6.7 just came out :)

https://www.python.org/downloads/release/python-367/

**Comment by thinkingserious** [comment]
Hello @moshemeirelles,<br /><br/>Thanks again for the PR!<br /><br />                                         You have earned 4 out of the 5 points needed to receive glorious SendGrid Hacktoberfest swag.<br /><br />                                         Please take a moment to checkout <a href="https://dx.sendgrid.com/hacktoberfest/issues">this link</a> to find more issues to get you past the required threshold or to simply continue the celebration.<br /><br />                                         Also, <strong>please be sure you have officially registered with us <a href="https://dx.sendgrid.com/hacktoberfest/join">here</a> by November 1, 2018</strong> to qualify.<br /><br />                                         If you have any questions you can email us at <a href="mailto:dx+hacktoberfest2018@sendgrid.com">dx+hacktoberfest2018@sendgrid.com</a>.<br /><br />                                         Thank you and Happy Hacktobering!<br /><br />                                         Team SendGrid

**Pull request closed without merging**
