### PR TITLE
Client cleanup

### PR DESCRIPTION
**Pull request by 3lnc**
### Checklist
- [x] I have made a material change to the repo (functionality, testing, spelling, grammar)
- [x] I have read the [Contribution Guide] and my PR follows them.
- [x] I updated my branch with the master branch.
- [x] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation about the functionality in the appropriate .md file
- [x] I have added in line documentation to the code I modified

### Short description of what this PR does:
Refactored `sendgrid.sendgrid.SendGridAPIClient`:
 - explicit params for `__init__` for proper code inspection (i.e. in IDE)
 - public `apikey` and `impersonate_subuser` attrs w/o descriptors
 - dropped unused `path`
 - more pythonic param dispatching
 - documentation for `__ini__`

### CODE REVIEW

**Comment by thinkingserious** [comment]
Thank you @3lnc! This is now on our backlog for a code review.

With Best Regards,

Elmer

**Comment by 3lnc** [comment]
Currently, this is backward-incompatible change because of dropping `**opts`. And tests currently uses `path` arg (which is ignored, and I'm not sure why it was included originally).

If this ever was public interface - either this change needs to be merged in major version, or we can add
```
def __init__(..., **opts)
    if opts: warnings.warn('unsupported args provided')
```
or simply `__init__(..., **_)` to ensure backward compatibility, and drop this later – during major release

**Comment by 3lnc** [comment]
Added `**opts` for backward compatibility, TODO note to remove it during major release, `DeprecationWarning`

**Comment by 3lnc** [comment]
Guys, is there any progress with code review queue? There's a lot of PRs (even from hacktoberfest) and no visual progress for at least a month.

 - Is there a chance for all that to be reviewed in near future?
 - Is it reasonable to propose more code changes now?

ping @thinkingserious

**Comment by thinkingserious** [comment]
Hi @3lnc,

Thanks for checking in!

This repo is actually next in line after PHP. We are almost done updating that repo and will then be focusing our efforts on this one, so your timing is perfect.

With Best Regards,

Elmer

**Comment by thinkingserious** [comment]
Hello @3lnc,<br /><br/>Thanks again for the PR!<br />                                              <br />We want to show our appreciation by sending                                              you some swag. Could you please fill out                                              <a href="https://dx.sendgrid.com/swag">this form</a> so we can send it to you? Thanks!                                             <br /><br />Team SendGrid DX

**Pull request merged**
