### PR TITLE
Typo fix (broken link)

### LINKED ISSUE #745: Broken link (MD filename typo)
#### Issue Summary

Broken link.

#### Steps to Reproduce

Open https://github.com/sendgrid/sendgrid-python/tree/master/use_cases and hit the `Transactional Templates` link, third from the bottom.

#### Technical details:

Caused by a typo. PR #746 submitted.

### PR DESCRIPTION
**Pull request by adamatan**
# Fixes #745 

### Checklist
- [x] I have made a material change to the repo (functionality, testing, spelling, grammar)
- [x] I have read the [Contribution Guide] and my PR follows them.
- [x] I updated my branch with the master branch.
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation about the functionality in the appropriate .md file
- [ ] I have added in line documentation to the code I modified

### Short description of what this PR does:
Simple typo fix for a broken link.

### CODE REVIEW

**Comment by SendGridDX** [comment]
[CLA assistant check](https://cla.sendgrid.com/sendgrid/sendgrid-python?pullRequest=746) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.sendgrid.com/sendgrid/sendgrid-python?pullRequest=746) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.sendgrid.com/check/sendgrid/sendgrid-python?pullRequest=746) it.</sub>

**Comment by misterdorm** [comment]
@adamatan  This looks good, but would you please rebase against the `v4` branch?  This repo is a little different and should only be PR'd against `v4`.  Thanks!

**Comment by adamatan** [comment]
Sure. Will get to it ASAP (EOY stuff).

**Comment by thinkingserious** [comment]
Hello @adamatan,

Just checking in. Thanks!

With Best Regards,

Elmer

**Comment by eshanholtz** [comment]
This fix has already been merged in a separate PR. Closing this PR.

**Pull request closed without merging**
