### PR TITLE
Improve code quality

### PR DESCRIPTION
**Pull request by andriisoldatenko**
## Summary
According to [CONTRIBUTING](https://github.com/sendgrid/sendgrid-python/blob/master/CONTRIBUTING.md#style-guidelines--naming-conventions) code should pass all pep8 and flake8 errors

On master branch we can see 
```
(python-sedgrid) ~/sendgrid-python$ flake8 . | wc -l
1201
OR
pep8 . | wc -l
1033
```
The goal of this PR to fix all errors.

## After this PR merged:
```
flake8 test/ | wc -l 
test/test_mail.py:212:80: E501 line too long (3359 > 79 characters)
```

## Checks on `sendgrid/` module:
```
flake8 sendgrid/ wc -l
```

## Unit tests:
```
----------------------------------------------------------------------
Ran 238 tests in 32.903s

OK
```

## Install checking tools:
```
pip install flake8 pep8 isort
```

### CODE REVIEW

**Comment by andriisoldatenko** [comment]
@thinkingserious Please review.
cc @vananabu

**Comment by thinkingserious** [comment]
Awesome @andriisoldatenko!

Could you please [sign our CLA](https://github.com/sendgrid/sendgrid-python/blob/master/CONTRIBUTING.md#cla) so I can review and merge? Thanks!

**Comment by andriisoldatenko** [comment]
@thinkingserious done.

**Comment by thinkingserious** [comment]
Hi @andriisoldatenko,

Could you please fix the conflicts in `test/test_sendgrid.py`? Thanks!

**Comment by andriisoldatenko** [comment]
@thinkingserious done.

**Comment by andriisoldatenko** [comment]
@thinkingserious  Can you please review again. Thanks

**Comment by SendGridDX** [comment]
Hi @andriisoldatenko,

Thanks again for the PR, please take a moment to fill out [this form]( https://docs.google.com/forms/d/e/1FAIpQLSelP4uF-wGJebxVYq1DYw5WzHomEUauab3YiqrshyCkRs0fqw/viewform#start=invite) so that we may send you some swag :)

**Pull request merged**
