### PR TITLE
Update config.py

### PR DESCRIPTION
**Pull request by ajiteshr7**
Better file handling

### CODE REVIEW

**Comment by SendGridDX** [comment]
[CLA assistant check](https://cla.sendgrid.com/sendgrid/sendgrid-python?pullRequest=423) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.sendgrid.com/sendgrid/sendgrid-python?pullRequest=423) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.sendgrid.com/check/sendgrid/sendgrid-python?pullRequest=423) it.</sub>

**Comment by mbernier** [comment]
It looks to me like this is just a refactoring of the way the lines are read from the file. Is that fair?

**Comment by ajiteshr7** [comment]
As when opening a file in 'for loop' we aren't keeping any explicit reference to the opened file. Hence to close the file we need to get dependent on the garbage collector, but that may mean that the resources aren't freed in a timely manner. Also if an exception occurs file will not get closed when using `for ... open`.
Python provides `with` to handle these cases and using `with` makes the code more readable.
More on this [here] (https://stackoverflow.com/questions/11130312/line-by-line-file-processing-for-loop-vs-with).

**Comment by mbernier** [comment]
Awesome, thank you for explaining this change @ajiteshr7!!

**Comment by thinkingserious** [comment]
Hello @ajiteshr7,<br /><br/>Thanks again for the PR!<br />                                              <br />It's <a href="https://sendgrid.com/blog/announcing-hacktoberfest-2017">HACKTOBERFEST</a>! We want to show our appreciation by sending                                              you some special Hacktoberfest swag. If you have not already, could you please fill out                                              <a href="https://dx.sendgrid.com/swag">this form</a> so we can send it to you? Thanks!                                             <br /><br />Team SendGrid DX

**Pull request merged**
