### PR TITLE
chore: fix vulnerability in starbank-ecdsa dependency

### LINKED ISSUE #1023: Dependency  starkbank-ecdsa forces high-severity vulnerability
Github has alerted us that our project has a high-severity vulnerability `starkbank-ecdsa` version 1.1.1. The requirements file here forces us to install it (see `requirements.txt`):

```
starkbank-ecdsa>=1.0.0,<2.0.0
```

Please fix this so we don't have to install this library to use sendgrid.

From the github alert:

```
GHSA-9wx7-jrvc-28mm
high severity
Vulnerable versions: < 2.0.1
Patched version: 2.0.1

An attacker can forge signatures on arbitrary messages that 
will verify for any public key. This may allow attackers to 
authenticate as any user within the Stark Bank platform, and 
bypass signature verification needed to perform operations 
on the platform, such as send payments and transfer funds. 
Additionally, the ability for attackers to forge signatures may 
impact other users and projects using these libraries in different 
and unforeseen ways.
```

PS - what does it use this library anyway? Seems odd that an email library depends on bank software.

### PR DESCRIPTION
**Pull request by hellno**
# Fixes #
Security vulnerability in starbank-ecdsa <=2.0.0
see https://github.com/advisories/GHSA-9wx7-jrvc-28mm for details

A short description of what this PR does.
Fixes #1023 

### Checklist
- [x] I acknowledge that all my contributions will be made under the project's license
- [ ] I have made a material change to the repo (functionality, testing, spelling, grammar)
- [X] I have read the [Contribution Guidelines](https://github.com/sendgrid/sendgrid-python/blob/main/CONTRIBUTING.md) and my PR follows them
- [X] I have titled the PR appropriately
- [X] I have updated my branch with the main branch
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added the necessary documentation about the functionality in the appropriate .md file
- [ ] I have added inline documentation to the code I modified

### CODE REVIEW

**Comment by thomwiggers** [comment]
Should probably update to 2.0.2, as there were more checks missing.

**Comment by kapilt** [comment]
@thomwiggers this should pick up 2.0.2 per the >= dep spec albeit setting the min to 2.0.2 is also good.

**Review by JenniferMah — APPROVED** [review]
Thanks for the PR @hellno!

**Comment by kapilt** [comment]
this also needs a release, else all apps depending on sendgrid library get flagged for the cve

**Pull request merged**
