### PR TITLE
Fix method_complexity issue in sendgrid/helpers/mail/ganalytics.py Fixes #498

### LINKED ISSUE #498: Fix "method_complexity" issue in sendgrid/helpers/mail/ganalytics.py
Function `get` has a Cognitive Complexity of 6 (exceeds 5 allowed). Consider refactoring.

https://codeclimate.com/github/sendgrid/sendgrid-python/sendgrid/helpers/mail/ganalytics.py#issue_59f639cd343eae000100006f

### PR DESCRIPTION
**Pull request by chetankm-cs**
# Fixes # 
Fixes #498 

### Checklist
- [x] I have made a material change to the repo (functionality, testing, spelling, grammar)
- [x] I have read the [Contribution Guide] and my PR follows them.
- [x] I updated my branch with the master branch.
- [x] I have added necessary documentation about the functionality in the appropriate .md file
- [x] I have added in line documentation to the code I modified

### Short description of what this PR does:
- Reduces the complexity of get and __init__ method

If you have questions, please send an email to [Sendgrid](mailto:dx@sendgrid.com), or file a Github Issue in this repository.

### CODE REVIEW

**Comment by SendGridDX** [comment]
[CLA assistant check](https://cla.sendgrid.com/sendgrid/sendgrid-python?pullRequest=514) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.sendgrid.com/sendgrid/sendgrid-python?pullRequest=514) before we can accept your contribution.<br/><hr/>**Chetan** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.sendgrid.com/check/sendgrid/sendgrid-python?pullRequest=514) it.</sub>

**Comment by thinkingserious** [comment]
@chetankm-cs

We can’t merge your PR without the CLA being signed. 

[ ] **Sign the CLA before November 3rd**
[ ] Tag @mbernier and @thinkingserious to let us know it is signed 

Then we will comment with a link to get your shirt!

**Comment by chetankm-cs** [comment]
@mbernier @thinkingserious 
I have already signed CLA but when I do a recheck the cla check still fails.
Please help ?

**Comment by thinkingserious** [comment]
Hi @chetankm-cs,

It looks like your commit was made by another user account "Chetan". Maybe the easiest thing to do is to re-create the PR under your @chetankm-cs account, reference this issue and close it.

With Best Regards,

Elmer

**Comment by chetankm-cs** [comment]
@thinkingserious I have changed the author, the CLA check has passed. Thanks.

**Comment by thinkingserious** [comment]
Thank you @chetankm-cs!

Please [click here](https://dx.sendgrid.com/swag) to fill out the form. Thanks!

**Comment by thinkingserious** [comment]
Hello @chetankm-cs,<br /><br/>Thanks again for the PR!<br />                                              <br />We appreciate your contribution and look forward to                                              continued collaboration. Thanks!                                             <br /><br />Team SendGrid DX

**Pull request merged**
