### PR TITLE
converted README to reStructuredText and version as plain text file

### PR DESCRIPTION
**Pull request by StrikerRUS**
### Checklist
- [x] I have made a material change to the repo (functionality, testing, spelling, grammar)
- [x] I have read the [Contribution Guide] and my PR follows them.
- [x] I updated my branch with the master branch.
- [x] I have added tests that prove my fix is effective or that my feature works
- [n/a] I have added necessary documentation about the functionality in the appropriate .md file
- [n/a] I have added in line documentation to the code I modified

### Short description of what this PR does:
- simplify processing of `__version__` attribute by retrieving it from the plain text file, not by executing the `.py` module.
- convert `README.md` to `README.rst` (appearance can be checked in this branch https://github.com/StrikerRUS/sendgrid-python/blob/pypi/README.rst), so `register.py` is not needed anymore.
- add Python versions badge.
   
- add PyPI version badge.

### CODE REVIEW

**Comment by SendGridDX** [comment]
[CLA assistant check](https://cla.sendgrid.com/sendgrid/sendgrid-python?pullRequest=634) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.sendgrid.com/sendgrid/sendgrid-python?pullRequest=634) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.sendgrid.com/check/sendgrid/sendgrid-python?pullRequest=634) it.</sub>

**Comment by thinkingserious** [comment]
Hello @StrikerRUS,<br /><br/>Thanks again for the PR!<br />                                              <br />It's <a href="https://sendgrid.com/blog/hacktoberfest-2018-has-arrived/">HACKTOBERFEST</a>! We want to show our appreciation by sending                                              you some special Hacktoberfest swag. If you have not already, could you please fill out                                              <a href="https://dx.sendgrid.com/hacktoberfest/join">this form</a> so we can send it to you? Thanks!                                             <br /><br />Team SendGrid DX

**Comment by thinkingserious** [comment]
Hi @StrikerRUS!

Could you please make this PR against the v4 branch? Thanks!

With Best Regards,

Elmer

**Comment by StrikerRUS** [comment]
@thinkingserious I'm so sorry, but I've failed to rebase the branch and moved all changes from this PR to #663.

**Pull request closed without merging**
